from pathlib import Path
import json,hashlib
out=Path(__file__).resolve().parent
load=lambda n:json.loads((out/n).read_text(encoding='utf-8'))
checks={
'1_crystal_center_transform':{'verdict':'FAIL','subchecks':{'executed_620_frames_zero_occupied':'PASS','units_note_and_translated_definition':'PASS','coordinate_frame_correctness':'FAIL'},'evidence':load('frame_diagnostics.json'),'rerun':load('pocket_rerun.json'),'reason':'bound_ref.pdb is not in the raw crystal frame. The ref-to-DCD centroid offset does not map the crystal center into the reference frame used for lig_p. ref_lig is additionally shifted while ref_bb stays unchanged, regressing RMSD.'},
'2_occupancy_provenance':{'verdict':'FAIL','subchecks':{'JSON_explicit_post_hoc':'PASS','final_report_consistent_post_hoc':'FAIL','figure4_explicit_post_hoc':'FAIL'},'reason':'JSON explicitly says ADDED POST HOC and original pre-registration had no occupancy criterion. final-report.md:214 still says pre-specified; manuscript repeats fixed-in-advance/pre-specified language and Figure 4 lacks audit/post-hoc attribution.'},
'3_R1_10_replay':{'verdict':'FAIL','subchecks':{'R1_10_appended':'PASS','RMSD_recomputed':'PASS','13_records_12_true_1_null':'PASS','summary_12_detected_1_delegated':'FAIL','hardcoded_replays_removed':'FAIL'},'evidence':load('replay_checks.json')},
'4_manifest_freeze':{'verdict':'FAIL','subchecks':{'five_levels_62_entries_no_self_reference':'PASS','all_root_hashes_current':'FAIL','research_log_current':'FAIL','reports_handoff':'FAIL','evidence_handoff':'PASS'},'reason':'61/62 root entries match. research-log.md expected 58520 bytes but current 60461; reports handoff artifact[5] SHA256 mismatch. Full hashes and checker outputs: manifest_checks.json.'},
'5_report_residuals':{'verdict':'FAIL','subchecks':{'obsolete_surface_sentence_removed_and_mapping_corrected':'PASS','banner_mean_max_labels':'PASS','3_1_ns_total':'PASS','hit_report_threshold':'FAIL','structure_analysis_ensemble_caveat':'FAIL','RMSD_agrees_with_current_output':'FAIL'},'reason':'hit-report.md:17 retains <= -7.0 reference claim; structure-analysis.md:61-62 retains no ensemble docking contradiction. final-report.md:211-212 reports 4.579/5.935 A while current rerun and producer output are 4.696/6.050 A.'}}
result={'role':'Fresh-session acceptance auditor, round 7','date':'2026-09-14','mode':'audit-repair (review only; no producer repairs)','capability':'partial-compute: saved trajectory and deterministic artifact checks','overall':'REJECT','G6_recommendation':'Remain BLOCKED. Correct frame handling and replay accounting, reconcile all reports, then freeze current bytes and obtain independent re-acceptance. No experimental-readiness claim.','checks':checks,'execution':{'pocket':'WSL ~/miniforge/envs/md/bin/python -B independent-audit/round7-acceptance/run_pocket.py; exit 0; exact producer computation with only output path redirected','replay':'Executed isolated R1-10 parsing/assignment block against current structures; inspected full replay source and saved records. Did not rerun live/TDC full suite.','handoff':'Installed ai-drug-discovery-team/scripts/check_handoff.py --root project --require artifacts, both bundles','write_scope':'Only independent-audit/round7-acceptance/; no producer files modified'},'root_manifest_sha256':hashlib.sha256(Path('audit_manifest.json').read_bytes()).hexdigest()}
result['report_review']=load('report_review.json')
result['checks']['5_report_residuals']['subchecks']['retired_COM_metric_occupancy_inference_removed']='FAIL'
(out/'round7_checks.json').write_text(json.dumps(result,indent=2,ensure_ascii=False),encoding='utf-8')
