from pathlib import Path
import json,hashlib
root=Path.cwd();out=root/'independent-audit/round6-acceptance'
def item(verdict,evidence,**kw):return dict(verdict=verdict,evidence=evidence,**kw)
m=json.loads((out/'manifest_checks.json').read_text());p=json.loads((out/'pocket_rerun.json').read_text());r=json.loads((out/'replay_results.json').read_text());z=json.loads((out/'reference_and_zn.json').read_text());rms=json.loads((out/'independent_rmsd.json').read_text())
checks={
'R5-1':item('FAIL',['WSL mdtraj rerun reproduces 620 frames, contacts [318,319,457,458], RMSD mean 4.579 / max 5.935 A; primary summary matches rerun.','Primary pocket_residence.json has summary and provenance only; units_note absent. Both superseded files exist.','scripts/pocket_residence_r5fix.py:83-88 assumes crystal frame equals saved reference frame; no crystal-to-reference transformation applied. Independent 2112-backbone fit changes center by 132.9814 A. Thus occupancy remains invalid despite numerical RMSD/contact repair.'],numerical_subcheck='PASS',rerun=p,reference_check=z),
'R5-2':item('PASS',['hit-report.md:205-214 distinguishes raw-record legacy RF500 from deduplicated MODEL-A refit, discloses 1/26 agreement, and attributes difference to training protocol. stochastic-approximate is absent.','final-report.md:239-247 contains matching lineage disclosure and explicit serialization withdrawal: no fitted estimator (MODEL-A refit, MODEL-B, or legacy) serialized; reproducibility limited to archived scores/refit outputs.']),
'R5-3':item('FAIL',['Windows Python replay completed through final output: 12 recorded checks, 11 detected, R1-3 null with designed parmed-unavailable fallback; claimed 13/12 is not reproduced.','R1-10 RMSD is computed but has no rec() call and is absent from replay records. Independent exhaustive per-element permutation RMSD = 1.7569671441021726 A, matching 1.757 A.','R1-2 uses hardcoded v1 values and arithmetic, R3-1 hardcodes observation and True, R3-6 uses literal values rather than reading the cited table. Counts are derived from records, but records are not all artifact-backed replays. R1-7 reads min catalytic-residue distance, not the Zn distance stated in its comment.','R1-6 and R3-3 execute generic canaries; R3-2 checks source substrings. These do not establish replay of the corresponding historical artifact defects.','WSL independently completed R1-3 topology epsilon check: 0.02662781997945352 kcal/mol. This does not change the submitted Windows replay count.'],observed_summary=r['summary'],independent_R1_10=rms),
'R5-4':item('FAIL',['Root has claimed level counts 29/12/7/2/5, but only 51/55 hashes and sizes match.','Stale leaves: pocket_residence.json, final-report.md, structure-analysis.md, research-log.md.','Both check_handoff.py invocations exit 1: reports artifacts[0,2,5], evidence artifacts[15] hash mismatch.','Append-after-hash root note exists but does not satisfy current-byte integrity. L2 also omits both new repair scripts, and L1 omits the executed-replay result.'],manifest_evidence='manifest_checks.json'),
'R5-T1':item('FAIL',['final-report.md:61 retains non-catalytic surface (235/342/374/375/376/405); :210 still lists only H319/T458; :223-224 retains pocket occupancy from the retired COM-imaged metric.']),
'R5-T2':item('FAIL',['hit-report.md:17 retains yields <= -7.0 despite table scores -6.96/-6.34/-6.01.']),
'R5-T3':item('FAIL',['structure-analysis.md:58-60 adds cross-crystal/5-snapshot ensembles and a rotamer caveat, but :61-62 still says and no ensemble docking was performed / campaign); the contradictory denial fragment remains.']),
'R5-T4':item('FAIL',['final-report.md:20-21 still presents 1.85-2.37 and 2.18-2.68 A as unlabeled ranges; mean/max labels later at :177-178 do not repair the banner.','The :61 summary labels bound v2 3.0 ns; :192 gives 100 ps heat + 3.0 ns production, but no explicit 3.1 ns total label appears.']),
'R5-T5':item('FAIL',['Assembled manuscript abstract :29-31 and Figure 4 :343-347 remove the literal pre-specified wording and acknowledge radius sensitivity (wording subcheck PASS).','Abstract still asserts specification recorded before the run; Figure 4 falsely attributes the occupancy conjunction to md/bound_analysis_pre_registered.json. That file contains RMSD/Zn metrics, no occupancy or 6 A/4.5 A criterion. Thus unsupported prospective provenance survives the rewording.'],literal_wording_subcheck='PASS'),
'R5-T6':item('PASS',['paper/MANUSCRIPT_DRAFT_v1.md:301-304 Positioning qualifies chain verification by recorded round-4 findings; :363-371 Data and code availability explicitly notes root self-reference, stale nested entry, unresolved revision integrity, and lack of adjudicated full-chain acceptance.'],scope='Assembled manuscript Positioning and Data availability')}
result=dict(role='Fresh-session acceptance auditor, round 6',date='2026-09-14',scope='Only four R5 repairs and requested residual regression sweep',overall='REJECT',G6_recommendation='Remain BLOCKED; repair deterministic failures and freeze again before fresh independent acceptance.',checks=checks,execution=dict(write_boundary='All created/modified artifacts restricted to independent-audit/round6-acceptance/. Producer scripts executed as local copies with only output/temp destinations redirected; replay additionally guarded against outside file writes and bytecode disabled. No producer computations changed.',pocket='WSL /root/miniforge/envs/md/bin/python -B; exit 0',replay='Windows C:/ProgramData/anaconda3/python.exe; full JSON and terminal completion observed. PowerShell stream redirection marked TDC informational stderr as NativeCommandError; no Python traceback or guard rejection.',independent_RMSD='Exhaustive permutations by element, first docking model, 11 heavy atoms; independent parser; no superposition.',handoff_checker='C:/Users/Gnimi/.agents/skills/ai-drug-discovery-team/scripts/check_handoff.py; --root workspace'),root_manifest_sha256=hashlib.sha256((root/'audit_manifest.json').read_bytes()).hexdigest())
(out/'round6_checks.json').write_text(json.dumps(result,indent=2,ensure_ascii=False),encoding='utf-8')
report='''# Round 6 acceptance audit

**Overall: REJECT. G6 recommendation: remain BLOCKED.**

Fresh-session re-acceptance, 2026-09-14. Scope: the four claimed round-5 repairs plus the six requested residual checks. Producer artifacts were not modified. This decision concerns artifact acceptance, not experimental validation.

| Repair | Verdict | Independent evidence |
|---|---|---|
| R5-1 Pocket selector/analysis | **FAIL; numerical subcheck PASS** | WSL rerun gives 620 frames, crystal contacts **[318,319,457,458]**, ligand RMSD **mean 4.579 / max 5.935 Å**. Zero-based mapping 122→206 through 404→488 is reproduced. However, primary JSON has **no units_note**, and the script still fails to transform the crystal center into the fitted reference frame. |
| R5-2 MODEL-A disclosure | **PASS** | Both reports disclose raw-record legacy versus deduplicated refit and 1/26 agreement. `stochastic-approximate` is absent from hit-report.md. Final report explicitly withdraws estimator serialization and limits reproducibility to archived scores/refit outputs. |
| R5-3 Executed replay | **FAIL** | Windows rerun records **12 checks / 11 detected / 1 delegated**, not 13/12. R1-10 is computed but never recorded. Several checks still use hardcoded observations rather than the cited artifacts. Independent R1-10 RMSD is **1.756967144 Å**, confirming the numerical repair. |
| R5-4 Manifest freeze | **FAIL** | **51/55** root hashes/sizes match; both handoff checkers exit **1**. The five level counts are correct, but the freeze is stale. |

## Unclosed mandatory defects

**Pocket reference frame.** `scripts/pocket_residence_r5fix.py:83–88` assumes the raw crystal centroid is already in the minimized-reference frame. Independent Kabsch fitting of 2,112 matched backbone atoms maps the center from **(−13.7129, −34.0981, −28.7246) Å** to **(52.1805, 56.8840, 42.4398) Å**, a **132.9814 Å** displacement. The script applies no such transform before comparing ligand-center distances. Reproducing zero occupancy therefore does not validate that calculation. The requested contacts and RMSD genuinely reproduce; both superseded JSON files exist. The primary JSON is now a 733-byte summary/provenance object and lacks the claimed units note.

**Replay semantics.** The script never calls `rec()` for R1-10. R1-2 uses literal values and arithmetic, R3-1 supplies literal observation text and `True`, and R3-6 checks a literal three-score list instead of reading the cited table. R1-7 reads catalytic-residue distances despite describing Zn distances in its comment. Generic hash canaries and a source-substring check are executed, but are not historical artifact replay. The R1-3 Windows fallback occurs as designed; an independent WSL ParmEd check confirms **ε = 0.02662781997945352 kcal/mol**. This does not repair the submitted replay denominator or evidentiary limitations.

**Freeze.** Root mismatches are `pocket_residence.json`, `final-report.md`, `structure-analysis.md`, and `research-log.md`. Reports handoff fails artifacts **0, 2, 5**; evidence handoff fails artifact **15**. Exact expected/actual hashes and sizes are recorded in `manifest_checks.json`. The append-after-hash note exists but cannot make stale hashes pass. The root also omits the two new repair scripts and executed-replay output from its relevant leaf lists.

## Residual regression sweep

| Check | Verdict | Evidence |
|---|---|---|
| R5-T1 Correct contact narrative | **FAIL** | final-report.md:61 retains the obsolete non-catalytic-surface residue sentence; :210 lists only H319/T458; :223–224 still infers pocket occupancy from the retired COM-imaged metric. |
| R5-T2 Reference threshold | **FAIL** | hit-report.md:17 still claims the references yield ≤ −7.0, contradicting its −6.96/−6.34/−6.01 table. |
| R5-T3 Ensemble caveat | **FAIL** | structure-analysis.md:58–60 adds the correct ensemble disclosure, but :61–62 retains “and no ensemble docking was performed / campaign)”. |
| R5-T4 Labels and timing | **FAIL** | final-report.md:20–21 banner ranges remain unlabeled; :61 says v2 3.0 ns. The protocol gives 100 ps heat + 3.0 ns production, but never explicitly labels 3.1 ns total. Later mean/max labels do not fix the banner. |
| R5-T5 Occupancy specification | **FAIL; literal rewording PASS** | Abstract and Figure 4 acknowledge radius sensitivity and remove the requested literal wording. However, abstract :30 still claims the specification predates the run, and Figure 4 :343–345 attributes the conjunction to `md/bound_analysis_pre_registered.json`, which contains no occupancy criterion or 6 Å/4.5 Å thresholds. The unsupported provenance claim remains. |
| R5-T6 Manifest qualifications | **PASS** | Assembled manuscript Positioning :301–304 and Data availability :363–371 explicitly qualify verification with round-4 root/nested findings and unresolved integrity. |

## Execution and evidence

Both producer scripts were copied into this audit directory with output/temp paths redirected, leaving their computations unchanged. The Windows replay ran behind a file-write boundary guard; bytecode writes were disabled. Its full results and terminal completion were observed. PowerShell labeled TDC informational stderr as a native-command error, but there was no Python traceback or write-guard rejection. The pocket rerun exited 0. No training, docking, or new simulation was performed.

Evidence: `round6_checks.json` (per-check verdicts), `manifest_checks.json`, `pocket_rerun.json`, `pocket_stdout.txt`, `replay_results.json`, `replay_stdout.txt`, `independent_rmsd.json`, and `reference_and_zn.json`; corresponding audit scripts are retained here. Independent RMSD uses exhaustive same-element permutations on 11 heavy atoms, without superposition or reuse of the producer's assignment routine.

Acceptance requires correcting the remaining frame/specification and replay defects, propagating report corrections, restoring the units disclosure, and freezing current leaves before nested and root manifests. Require every root entry and both handoff checks to pass before another fresh acceptance review.
'''
(out/'round6-acceptance.md').write_text(report,encoding='utf-8')
print('Wrote round6-acceptance.md and round6_checks.json; overall REJECT')
